/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Backend.DBConnection;

/**
 *
 * @author bijon
 */
public class AssignmentForm extends javax.swing.JFrame {

    /**
     * Creates new form AssignmentForm
     */
    public AssignmentForm() {
        initComponents();
           loadDropdowns(); // Fill combo boxes
        loadAssignmentsToTable(); // Show all assignments
    }

    
       // Load shipment and driver IDs into dropdowns
    private void loadDropdowns() {
        try (Connection con = DBConnection.getConnection()) {
            comboShipment.removeAllItems();
            comboDriver.removeAllItems();

            ResultSet rs1 = con.createStatement().executeQuery("SELECT id FROM shipments");
            while (rs1.next()) {
                comboShipment.addItem(String.valueOf(rs1.getInt("id")));
            }

            ResultSet rs2 = con.createStatement().executeQuery("SELECT driver_id FROM drivers");
            while (rs2.next()) {
                comboDriver.addItem(String.valueOf(rs2.getInt("driver_id")));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error loading dropdowns!");
            e.printStackTrace();
        }
    }
    
    private boolean validateForm() {
        if (comboShipment.getSelectedItem() == null ||
            comboDriver.getSelectedItem() == null ||
            txtDate.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Please fill all fields!");
            return false;
        }

        if (!txtDate.getText().matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "⚠️ Date must be in yyyy-mm-dd format!");
            return false;
        }

        return true;
    }
private void assignDriver() {
        if (!validateForm()) return;

        int shipmentId = Integer.parseInt(comboShipment.getSelectedItem().toString());
        int driverId = Integer.parseInt(comboDriver.getSelectedItem().toString());
        String date = txtDate.getText().trim();

        try (Connection con = DBConnection.getConnection()) {
            String sql = "INSERT INTO assignments (shipment_id, driver_id, assignment_date) VALUES (?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, shipmentId);
            ps.setInt(2, driverId);
            ps.setDate(3, Date.valueOf(date));

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "✅ Assignment successful!");
                loadAssignmentsToTable();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Assignment failed!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error assigning driver!");
            e.printStackTrace();
        }
    }
 private void loadAssignmentsToTable() {
        try (Connection con = DBConnection.getConnection()) {
            String sql = "SELECT shipment_id, driver_id, assignment_date FROM assignments";
            ResultSet rs = con.createStatement().executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel(
                new String[] {"Shipment ID", "Driver ID", "Date"}, 0
            );

            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("shipment_id"),
                    rs.getInt("driver_id"),
                    rs.getDate("assignment_date").toString()
                });
            }

            tableAssign.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error loading assignments!");
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
       private void clearForm() {
        comboShipment.setSelectedIndex(0);
        comboDriver.setSelectedIndex(0);
        txtDate.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboShipment = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboDriver = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAssign = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Shipment and Driver Assignment");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel3.setText("Shipment ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 87, -1, -1));

        comboShipment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboShipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 84, 223, -1));

        jLabel4.setText(" Driver ID  ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 135, -1, -1));

        comboDriver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 132, 223, -1));

        jLabel5.setText("Assignment Date ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 189, -1, -1));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 183, 223, -1));

        tableAssign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Shipment ID", "Driver ID", "Date"
            }
        ));
        jScrollPane1.setViewportView(tableAssign);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, 170));

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        jPanel1.add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
         clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        assignDriver();
    }//GEN-LAST:event_btnAssignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> comboDriver;
    private javax.swing.JComboBox<String> comboShipment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAssign;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
