/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import Backend.DBConnection;
import Backend.DistanceCalculator;
import static Backend.DistanceCalculator.getDistanceAndTime;
import backend.SessionManager;
import static java.awt.geom.Point2D.distance;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Map;
import static java.util.Map.entry;
import javax.swing.JOptionPane;

/**
 *
 * @author bijon
 */
public class book_delivery extends javax.swing.JFrame {
    
   


    /**
     * Creates new form book_delivery
     */
    public book_delivery() {
     
        
        initComponents();
        int customerId = SessionManager.getCustomerId();
        String customerName = SessionManager.getCustomerName();

// Optional: Display or use
System.out.println("Welcome ID: " + customerId + " | Name: " + customerName);
        
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reciever = new javax.swing.JTextField();
        contents = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        typetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("reciever's address");

        jLabel2.setText("Contents");

        reciever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recieverActionPerformed(evt);
            }
        });

        jButton1.setText("book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Package Type");

        typetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typetxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reciever, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(contents)
                            .addComponent(typetxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton1)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(reciever, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String receiverAddress = reciever.getText().trim();
        String contentDetails = contents.getText().trim();
        String type = typetxt.getText().trim();

        if (receiverAddress.isEmpty() || contentDetails.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ All fields must be filled!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int customerId = SessionManager.getCustomerId();
            Connection conn = DBConnection.getConnection();

            // 🔍 Get sender address from customer table
            String senderAddress = "";
            String fetchQuery = "SELECT address FROM customers WHERE customer_id = ?";
            PreparedStatement pstFetch = conn.prepareStatement(fetchQuery);
            pstFetch.setInt(1, customerId);
            ResultSet rs = pstFetch.executeQuery();

            if (rs.next()) {
                senderAddress = rs.getString("address");
            } else {
                JOptionPane.showMessageDialog(this, "❌ Customer not found!", "Error", JOptionPane.ERROR_MESSAGE);
                conn.close();
                return;
            }
            
            Map<String, String> Newmap = getDistanceAndTime(senderAddress, receiverAddress );
            
            String distance =Newmap.get("distance");
            String duration =Newmap.get("duration");
            String cleanedDistance = distance.replace("km", "").trim();
            double dist = Double.parseDouble(cleanedDistance);
            String estimatedTimeFormatted = "00:" + duration.replace("mins", "").trim() + ":00";
            
            
            String sql = "INSERT INTO shipments (customer_id, sender, receiver, contents, type, distance, duration) "
           + "VALUES (?, ?, ?, ?, ?, ?, ?)"; // Only 7 values!

                PreparedStatement stmt = conn.prepareStatement(sql);

                    stmt.setInt(1, customerId);
                    stmt.setString(2, senderAddress);
                    stmt.setString(3, receiverAddress);
                    stmt.setString(4, contentDetails);
                    stmt.setString(5, type);
                    stmt.setDouble(6, dist);                    // ✅ correct index
                    stmt.setString(7, estimatedTimeFormatted);  // ✅ correct index

            stmt.executeUpdate();                       // ✅ use correct variable

            JOptionPane.showMessageDialog(this, "✅ Delivery booked successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            reciever.setText("");
            contents.setText("");

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Failed to book delivery!\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void recieverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recieverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recieverActionPerformed

    private void typetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typetxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book_delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book_delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book_delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book_delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         java.awt.EventQueue.invokeLater(() -> {
            SessionManager.setCustomer(1, "Test User"); // Only for testing, remove in production
            new book_delivery().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contents;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField reciever;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables
}
