/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import Backend.DBConnection;
import Backend.DistanceCalculator;
import static Backend.DistanceCalculator.getDistanceAndTime;
import Backend.SimpleMailer;
import backend.SessionManager;
import static java.awt.geom.Point2D.distance;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Map;
import static java.util.Map.entry;
import javax.swing.JOptionPane;

/**
 *
 * @author bijon
 */
public class book_delivery extends javax.swing.JFrame {
    
   


    /**
     * Creates new form book_delivery
     */
    public book_delivery() {
     
        
        initComponents();
        int customerId = SessionManager.getCustomerId();
        String customerName = SessionManager.getCustomerName();

// Optional: Display or use
System.out.println("Welcome ID: " + customerId + " | Name: " + customerName);
        
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reciever = new javax.swing.JTextField();
        contents = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        typetxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Reciever's address");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Contents");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        reciever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recieverActionPerformed(evt);
            }
        });
        getContentPane().add(reciever, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 182, -1));
        getContentPane().add(contents, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 174, 182, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book Delivery");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 286, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Package Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        typetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typetxtActionPerformed(evt);
            }
        });
        getContentPane().add(typetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 218, 182, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 328, 77, 29));

        Back.setBackground(new java.awt.Color(0, 102, 0));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Book a Delivery...");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 45, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String receiverAddress = reciever.getText().trim();
        String contentDetails = contents.getText().trim();
        String type = typetxt.getText().trim();

        if (receiverAddress.isEmpty() || contentDetails.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ All fields must be filled!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int customerId = SessionManager.getCustomerId();
            Connection conn = DBConnection.getConnection();

            // 🔍 Get sender address from customer table
            String senderAddress = "";
            String fetchQuery = "SELECT address FROM customers WHERE customer_id = ?";
            PreparedStatement pstFetch = conn.prepareStatement(fetchQuery);
            pstFetch.setInt(1, customerId);
            ResultSet rs = pstFetch.executeQuery();

            if (rs.next()) {
                senderAddress = rs.getString("address");
            } else {
                JOptionPane.showMessageDialog(this, "❌ Customer not found!", "Error", JOptionPane.ERROR_MESSAGE);
                conn.close();
                return;
            }
            
            Map<String, String> Newmap = getDistanceAndTime(senderAddress, receiverAddress );
            
            String distance =Newmap.get("distance");
            String duration =Newmap.get("duration");
            String cleanedDistance = distance.replace("km", "").trim();
            double dist = Double.parseDouble(cleanedDistance);
            String estimatedTimeFormatted = "00:" + duration.replace("mins", "").trim() + ":00";
            
            
            String sql = "INSERT INTO shipments (customer_id, sender, receiver, contents, type, distance, duration) "
           + "VALUES (?, ?, ?, ?, ?, ?, ?)"; // Only 7 values!

                PreparedStatement stmt = conn.prepareStatement(sql);

                    stmt.setInt(1, customerId);
                    stmt.setString(2, senderAddress);
                    stmt.setString(3, receiverAddress);
                    stmt.setString(4, contentDetails);
                    stmt.setString(5, type);
                    stmt.setDouble(6, dist);                    // ✅ correct index
                    stmt.setString(7, estimatedTimeFormatted);  // ✅ correct index

            stmt.executeUpdate();                       // ✅ use correct variable

            JOptionPane.showMessageDialog(this, "✅ Delivery booked successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            reciever.setText("");
            contents.setText("");

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Failed to book delivery!\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        String email="";
        
        try {
        int customerId = SessionManager.getCustomerId();
        Connection con = DBConnection.getConnection();
        String sql = "SELECT email FROM customers WHERE id = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setInt(1, customerId);

        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            email = rs.getString("email");
        }

    } catch (Exception e) {
        e.printStackTrace();
        System.out.println("❌ Customer email not found.");
    }
        
    SimpleMailer.sendEmail(email, "Order Confirmed", "Order is on the way");
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void recieverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recieverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recieverActionPerformed

    private void typetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typetxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SessionManager.logout();
        new login().setVisible(true);
        this.dispose();
        System.out.println("Logged out successfully.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new user_dashboard().setVisible(true); // Go back to dashboard
    this.dispose(); // Close current form
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book_delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book_delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book_delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book_delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         java.awt.EventQueue.invokeLater(() -> {
            SessionManager.setCustomer(1, "Test User"); // Only for testing, remove in production
            new book_delivery().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField contents;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField reciever;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables
}
