/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import Backend.DBConnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Backend.DBConnection;
import backend.SessionManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KT
 */
public class DriverForm extends javax.swing.JFrame {

    /**
     * Creates new form DriverForm
     */

    public DriverForm() {
        initComponents();
    }
    public void clearFields() {
    fullnametxt.setText("");
    nictxt.setText("");
    pnumbertxt.setText("");
    emailtxt.setText("");
    vehicletxt.setText("");
    buttonGroup1.clearSelection(); // group your radio buttons in NetBeans GUI
}
    
public void loadTable() {
    try {
        Connection con = DBConnection.getConnection();
        String sql = "SELECT * FROM drivers"; // your table name
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        // Get metadata for column names
        ResultSetMetaData rsmd = rs.getMetaData();
        int colCount = rsmd.getColumnCount();

        // Table model to hold data
        DefaultTableModel model = new DefaultTableModel();

        // Add column names
        for (int i = 1; i <= colCount; i++) {
            model.addColumn(rsmd.getColumnName(i));
        }

        // Add rows
        while (rs.next()) {
            Object[] row = new Object[colCount];
            for (int i = 1; i <= colCount; i++) {
                row[i - 1] = rs.getObject(i);
            }
            model.addRow(row);
        }

        driverTable.setModel(model); // set data to JTable

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "❌ Error loading table: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.y
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fullnametxt = new javax.swing.JTextField();
        nictxt = new javax.swing.JTextField();
        pnumbertxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vehicletxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        driverTable = new javax.swing.JTable();
        Submitbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        loadbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Full Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 95, -1, -1));

        jLabel3.setText("NIC Number");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 139, -1, -1));

        jLabel4.setText("Phone Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 183, -1, -1));

        jLabel5.setText("Email Address");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 227, -1, -1));

        fullnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnametxtActionPerformed(evt);
            }
        });
        jPanel2.add(fullnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 90, 120, -1));
        jPanel2.add(nictxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 134, 120, -1));
        jPanel2.add(pnumbertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 178, 120, -1));

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel2.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 222, 120, -1));

        jLabel7.setText("Vehicle Number");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        vehicletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicletxtActionPerformed(evt);
            }
        });
        jPanel2.add(vehicletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 71, -1));

        jLabel8.setText("Status");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        driverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        driverTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                driverTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(driverTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 618, 179));

        Submitbtn.setBackground(new java.awt.Color(0, 0, 153));
        Submitbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        Submitbtn.setText("ADD");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        clearbtn.setBackground(new java.awt.Color(0, 0, 153));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        updatebtn.setBackground(new java.awt.Color(0, 0, 153));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel2.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Active");
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Inactive");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        loadbtn.setBackground(new java.awt.Color(0, 0, 153));
        loadbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loadbtn.setForeground(new java.awt.Color(255, 255, 255));
        loadbtn.setText("LOAD");
        loadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbtnActionPerformed(evt);
            }
        });
        jPanel2.add(loadbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Driver Management Form");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 24, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Logout");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 500, 100, 40));

        Back.setBackground(new java.awt.Color(0, 102, 0));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.setBorder(null);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 80, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 540));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fullnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnametxtActionPerformed
        
    }//GEN-LAST:event_fullnametxtActionPerformed

    private void vehicletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicletxtActionPerformed

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed

        String name = fullnametxt.getText().trim();
    String phone = pnumbertxt.getText().trim();
    String nic = nictxt.getText().trim();
    String mail = emailtxt.getText().trim();
    String vehicleno = vehicletxt.getText().trim();

    String status = ""; // From radio buttons
    if (jRadioButton1.isSelected()) {
        status = "Active";
    } else if (jRadioButton2.isSelected()) {
        status = "Inactive";
    }

    try {
        // Validation
        if (name.isEmpty() || mail.isEmpty() || phone.isEmpty() || nic.isEmpty() || vehicleno.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields ❗", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ✅ Get connection
        Connection con = DBConnection.getConnection();

        // ✅ SQL with all 7 columns (except auto-increment ID)
        String sql = "INSERT INTO drivers (full_name, nic_number, phone, email, vehicle_number, status, created_at) " +
                     "VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)";

        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1, name);
        stmt.setString(2, nic);
        stmt.setString(3, phone);
        stmt.setString(4, mail);
        stmt.setString(5, vehicleno);
        stmt.setString(6, status);

        int rows = stmt.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "✅ Driver added successfully!");
            clearFields();  // Clear inputs
            loadDrivers();  // Reload your JTable if exists
        }

        con.close(); // Always close

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "❌ Error: " + ex.getMessage());
        ex.printStackTrace();
    }

    
    }//GEN-LAST:event_SubmitbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clearFields();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void loadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbtnActionPerformed
       loadTable();

    }//GEN-LAST:event_loadbtnActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void driverTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driverTableMouseClicked
        // TODO add your handling code here:
    int selectedRow = driverTable.getSelectedRow();
    if (selectedRow != -1) {
        fullnametxt.setText(driverTable.getValueAt(selectedRow, 1).toString());  // full_name
        nictxt.setText(driverTable.getValueAt(selectedRow, 2).toString());      // nic_number
        pnumbertxt.setText(driverTable.getValueAt(selectedRow, 3).toString());  // phone
        emailtxt.setText(driverTable.getValueAt(selectedRow, 4).toString());    // email
        vehicletxt.setText(driverTable.getValueAt(selectedRow, 5).toString());  // vehicle_number

        // ✅ Set radio button for status
        String status = driverTable.getValueAt(selectedRow, 6).toString();      // status
        if (status.equalsIgnoreCase("Active")) {
            jRadioButton1.setSelected(true);  // Active
        } else {
            jRadioButton2.setSelected(true);  // Inactive
        }

    }
    
    }//GEN-LAST:event_driverTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SessionManager.logout();
        new login().setVisible(true);
        this.dispose();
        System.out.println("Logged out successfully.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SessionManager.logout();
        new login().setVisible(true);
        this.dispose();
        System.out.println("Logged out successfully.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SessionManager.logout();
        new login().setVisible(true);
        this.dispose();
        System.out.println("Logged out successfully.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new dashboard().setVisible(true); // Go back to dashboard
        this.dispose(); // Close current form
    }//GEN-LAST:event_BackActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
    /// ✅ Get selected row index
    int row = driverTable.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "⚠️ Please select a driver to update.");
        return;
    }

    try {
        // 🔑 Get ID of the selected driver (from column 0)
        int driverId = (int) driverTable.getValueAt(row, 0);

        // 📝 Get input values from form
        String name = fullnametxt.getText().trim();
        String nic = nictxt.getText().trim();
        String phone = pnumbertxt.getText().trim();
        String email = emailtxt.getText().trim();
        String vehicleNo = vehicletxt.getText().trim();

        // 🚦 Get status from radio buttons
        String status = "";
        if (jRadioButton1.isSelected()) {
            status = "Active";
        } else if (jRadioButton2.isSelected()) {
            status = "Inactive";
        }

        // ⚠️ Validation
        if (name.isEmpty() || nic.isEmpty() || phone.isEmpty() || email.isEmpty() || vehicleNo.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "❗ Please fill in all fields.");
            return;
        }

        // 🛠️ Update in DB
        Connection conn = DBConnection.getConnection();
        String sql = "UPDATE drivers SET full_name=?, nic_number=?, phone=?, email=?, vehicle_number=?, status=? WHERE driver_id=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, name);
        pst.setString(2, nic);
        pst.setString(3, phone);
        pst.setString(4, email);
        pst.setString(5, vehicleNo);
        pst.setString(6, status);
        pst.setInt(7, driverId); // 🧠 Use selected row ID

        int rowsAffected = pst.executeUpdate();
        conn.close();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "✅ Driver updated successfully!");
            loadDrivers(); // 🔁 Refresh table (or call loadDrivers())
        } else {
            JOptionPane.showMessageDialog(this, "⚠️ No changes made or driver not found.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "❌ Failed to update driver.\n" + e.getMessage());
    }



    }//GEN-LAST:event_updatebtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverForm().setVisible(true);               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Submitbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTable driverTable;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fullnametxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadbtn;
    private javax.swing.JTextField nictxt;
    private javax.swing.JTextField pnumbertxt;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField vehicletxt;
    // End of variables declaration//GEN-END:variables

    private void loadDrivers() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
