/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import Backend.DBConnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Backend.DBConnection;
import backend.SessionManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KT
 */
public class DriverForm extends javax.swing.JFrame {

    /**
     * Creates new form DriverForm
     */

    public DriverForm() {
        initComponents();
    }
    public void clearFields() {
    fullnametxt.setText("");
    nictxt.setText("");
    pnumbertxt.setText("");
    emailtxt.setText("");
    routeBox.setSelectedIndex(0);
    vehicletxt.setText("");
    buttonGroup1.clearSelection(); // group your radio buttons in NetBeans GUI
}
    
public void loadTable() {
    try {
        Connection con = DBConnection.getConnection();
        String sql = "SELECT * FROM drivers"; // your table name
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        // Get metadata for column names
        ResultSetMetaData rsmd = rs.getMetaData();
        int colCount = rsmd.getColumnCount();

        // Table model to hold data
        DefaultTableModel model = new DefaultTableModel();

        // Add column names
        for (int i = 1; i <= colCount; i++) {
            model.addColumn(rsmd.getColumnName(i));
        }

        // Add rows
        while (rs.next()) {
            Object[] row = new Object[colCount];
            for (int i = 1; i <= colCount; i++) {
                row[i - 1] = rs.getObject(i);
            }
            model.addRow(row);
        }

        driverTable.setModel(model); // set data to JTable

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "❌ Error loading table: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.y
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        routeBox = new javax.swing.JComboBox<>();
        fullnametxt = new javax.swing.JTextField();
        nictxt = new javax.swing.JTextField();
        pnumbertxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vehicletxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        driverTable = new javax.swing.JTable();
        Submitbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        loadbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Full Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 95, -1, -1));

        jLabel3.setText("NIC Number");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 139, -1, -1));

        jLabel4.setText("Phone Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 183, -1, -1));

        jLabel5.setText("Email Address");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 227, -1, -1));

        routeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(routeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 90, -1, -1));

        fullnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnametxtActionPerformed(evt);
            }
        });
        jPanel2.add(fullnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 90, 71, -1));
        jPanel2.add(nictxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 134, 71, -1));
        jPanel2.add(pnumbertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 178, 71, -1));

        jLabel6.setText("Assigned Route");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 95, -1, -1));

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel2.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 222, 71, -1));

        jLabel7.setText("Vehicle Number");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 155, -1, -1));

        vehicletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicletxtActionPerformed(evt);
            }
        });
        jPanel2.add(vehicletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 150, 71, -1));

        jLabel8.setText("Status");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 213, -1, -1));

        driverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        driverTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                driverTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(driverTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 618, 179));

        Submitbtn.setBackground(new java.awt.Color(0, 0, 153));
        Submitbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        Submitbtn.setText("ADD");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        clearbtn.setBackground(new java.awt.Color(0, 0, 153));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        updatebtn.setBackground(new java.awt.Color(0, 0, 153));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("UPDATE");
        jPanel2.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Active");
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 211, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Inactive");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 211, -1, -1));

        loadbtn.setBackground(new java.awt.Color(0, 0, 153));
        loadbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loadbtn.setForeground(new java.awt.Color(255, 255, 255));
        loadbtn.setText("LOAD");
        loadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbtnActionPerformed(evt);
            }
        });
        jPanel2.add(loadbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Driver Management Form");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 24, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Logout");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 500, 100, 40));

        Back.setBackground(new java.awt.Color(0, 102, 0));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.setBorder(null);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 80, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 540));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fullnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnametxtActionPerformed
        
    }//GEN-LAST:event_fullnametxtActionPerformed

    private void vehicletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicletxtActionPerformed

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed
    Submitbtn.addActionListener(e -> {
    String name = fullnametxt.getText();
    String phone = pnumbertxt.getText();
    String license = nictxt.getText();
    String address = emailtxt.getText();
    String mail = emailtxt.getText();

    try {
        if (name.isEmpty() || mail.isEmpty() || phone.isEmpty() || address.isEmpty() || (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) ) {
        JOptionPane.showMessageDialog(null, "Please fill all fields ❗", "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }
        // ✅ Use your reusable DB connection class
        Connection con = DBConnection.getConnection();

        String sql = "INSERT INTO drivers (full_name, phone, nic_number, email) VALUES (?, ?, ?, ?)";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1, name);
        stmt.setString(2, phone);
        stmt.setString(3, license);
        stmt.setString(4, address);

        int rows = stmt.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "✅ Driver added successfully!");
            clearFields();  // Clear input fields
            loadDrivers();  // Reload JTable if applicable
        }

        con.close();  // Always close the connection
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "❌ Error: " + ex.getMessage());
        ex.printStackTrace(); // Optional: print stack trace for debug
    }
});
    
    }//GEN-LAST:event_SubmitbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clearFields();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void loadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbtnActionPerformed
        loadbtn.addActionListener(e -> loadTable());

    }//GEN-LAST:event_loadbtnActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void driverTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driverTableMouseClicked
     //   int selectedRow = tableShipments.getSelectedRow();
    //if (selectedRow != -1) {
  //      txtSender.setText(tableShipments.getValueAt(selectedRow, 1).toString());
  //      txtReceiver.setText(tableShipments.getValueAt(selectedRow, 2).toString());
  //      txtContents.setText(tableShipments.getValueAt(selectedRow, 3).toString());
  ///      jComboBox1.setSelectedItem(tableShipments.getValueAt(selectedRow, 4).toString());
   //     txtEta.setText(tableShipments.getValueAt(selectedRow, 5).toString());
    
    }//GEN-LAST:event_driverTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SessionManager.logout();
        new login().setVisible(true);
        this.dispose();
        System.out.println("Logged out successfully.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SessionManager.logout();
        new login().setVisible(true);
        this.dispose();
        System.out.println("Logged out successfully.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SessionManager.logout();
        new login().setVisible(true);
        this.dispose();
        System.out.println("Logged out successfully.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new dashboard().setVisible(true); // Go back to dashboard
        this.dispose(); // Close current form
    }//GEN-LAST:event_BackActionPerformed
    
    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverForm().setVisible(true);               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Submitbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTable driverTable;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fullnametxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadbtn;
    private javax.swing.JTextField nictxt;
    private javax.swing.JTextField pnumbertxt;
    private javax.swing.JComboBox<String> routeBox;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField vehicletxt;
    // End of variables declaration//GEN-END:variables

    private void loadDrivers() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
